algo = input('Digite algo: ')
print('O tipo primitivo deste valor é ', type(algo))
print('É um valor numerico?', algo.isnumeric())
print('Só tem espaços?', algo.isspace())
print('É alphanumerico?', algo.isalnum())
print('É alphabetico?', algo.isalpha())
print('É titulo?', algo.istitle())
print('É somente caixa alta?', algo.isupper())
print('É somente caixa baixa?', algo.islower())
